# Generated by Django 5.1.1 on 2025-05-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldapp', '0006_alter_bid_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
