# Generated by Django 5.1.1 on 2025-05-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldapp', '0007_alter_contract_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
